version: "3.8"

services:
  app:
    build: ./app
    container_name: myapp
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: testdb
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myphpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # ----------------- Exporters -----------------
  node-exporter:
    image: prom/node-exporter
    container_name: mynodeexporter
    ports:
      - "9100:9100"

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    environment:
      DATA_SOURCE_NAME: "root:rootpass@(db:3306)/"
    ports:
      - "9104:9104"
    depends_on:
      - db

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - "-nginx.scrape-uri=http://mynginx:80/stub_status"
    ports:
      - "9113:9113"
    depends_on:
      - nginx

  # ----------------- Monitoring stack -----------------
  prometheus:
    image: prom/prometheus
    container_name: myprometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    container_name: mygrafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
volumes:
  db_data:
  grafana-data:
